/* eslint-disable no-unused-vars */
/** Редактируйте этот файл — все данные поездки для мамы. */
const TRIP = {
  meta: {
    title: "Happy Mama Tour",
    subtitle: "Москва → Петербург с мамой",
    start: "2026-08-03",
    end: "2026-08-10",
    nights: 7,
    travelers: 2,
    budget: 85000,
    version: "1.0",
  },

  hotel: {
    name: "← укажите название отеля",
    address: "← улица, дом, Санкт-Петербург",
    lat: 59.9343,
    lon: 30.3351,
    checkIn: "2026-08-03",
    checkOut: "2026-08-10",
    checkInFrom: "14:00",
    lateCheckIn: true,
    phone: "+7 …",
    bookingRef: "← номер брони",
    costPerNight: 3500,
    nights: 7,
    notes: "Предупредите отель о позднем заезде (~00:30). Нужен паспорт обоих.",
  },

  tickets: [
    {
      id: "train-out",
      label: "Поезд туда · «Аврора»",
      date: "2026-08-03",
      train: "746У «Аврора»",
      from: "Москва, Ленинградский вокзал",
      to: "Санкт-Петербург, Московский вокзал",
      depart: "17:45",
      arrive: "23:05",
      weekday: "понедельник",
      seats: "← купе, места …",
      cost: 2600,
      costNote: "1300 ₽ × 2",
      link: "https://www.rzd.ru/",
    },
    {
      id: "train-back",
      label: "Поезд обратно · «Аврора»",
      date: "2026-08-10",
      train: "746У «Аврора»",
      from: "Санкт-Петербург, Московский вокзал",
      to: "Москва, Ленинградский вокзал",
      depart: "17:20",
      arrive: "22:58",
      weekday: "понедельник",
      seats: "← купе, места …",
      cost: 2600,
      costNote: "1300 ₽ × 2",
      link: "https://www.rzd.ru/",
    },
  ],

  /** Готовые траты (фиксированные) — дополняются суммами из шагов дней. */
  budgetFixed: [
    { id: "hotel", label: "Отель (7 ночей)", amount: 0, note: "считается из hotel.costPerNight" },
    { id: "train", label: "Ж/д билеты (туда + обратно)", amount: 0, note: "5200 ₽ · 1300 × 2 × 2 направления" },
    { id: "palaces", label: "Билеты в музеи (ориентир)", amount: 12000, note: "Екатерининский, Петергоф, Павловск" },
    { id: "food", label: "Еда и кафе (ориентир)", amount: 28000, note: "~3500 ₽/день на двоих" },
    { id: "misc", label: "Сувениры и мелочи", amount: 5000, note: "" },
  ],

  mustSee: [
    { id: "pushkin", name: "Екатерининский дворец · Пушкин", day: "5 авг", done: false },
    { id: "peterhof", name: "Петергоф · фонтаны", day: "6 авг", done: false },
    { id: "vyborg", name: "Выборг · замок и Монрепо", day: "7 авг", done: false },
    { id: "valaam", name: "Валаам · монастырь", day: "8 авг", done: false },
    { id: "rest", name: "День отдыха · без выездов", day: "9 авг", done: false },
    { id: "embank", name: "Невская перспектива · вечерняя прогулка", day: "4 авг", done: false },
  ],

  packing: [
    { id: "docs", text: "Паспорта + распечатка брони отеля", done: false },
    { id: "tickets", text: "Билеты на поезд (электронные + скрин)", done: false },
    { id: "rain", text: "Зонт и лёгкая куртка — август бывает дождливым", done: false },
    { id: "shoes", text: "Удобная обувь для парков и брусчатки", done: false },
    { id: "pills", text: "Лекарства, которые принимаете постоянно", done: false },
    { id: "charger", text: "Powerbank и зарядки", done: false },
  ],

  days: [
    {
      id: "d1",
      date: "2026-08-03",
      label: "День 1 · Приезд",
      weekday: "понедельник",
      summary: "746У «Аврора» · Московский → каршеринг → отель",
      steps: [
        {
          time: "17:45",
          title: "Отправление · Ленинградский вокзал",
          transport: "train",
          detail: "Поезд 746У «Аврора». Москва → Санкт-Петербург. Проверьте вагон и места заранее.",
          address: "Москва, Ленинградский вокзал, Комсомольская пл.",
          lat: 55.7762,
          lon: 37.6553,
          cost: null,
        },
        {
          time: "23:05",
          title: "Прибытие · Московский вокзал",
          transport: "train",
          detail: "Понедельник, 3 августа. Выход на площадь Восстания, включите интернет.",
          address: "Санкт-Петербург, Московский вокзал, пл. Восстания",
          lat: 59.9287,
          lon: 30.3617,
          cost: null,
        },
        {
          time: "23:15",
          title: "Каршеринг → отель",
          transport: "carshare",
          detail: "Яндекс Драйв / Делимобиль / Ситидрайв — машина у Московского вокзала. ~15–25 мин до центра.",
          address: "Московский вокзал → отель",
          cost: 900,
          costNote: "ориентир + парковка у отеля",
          tips: ["Фото машины при посадке", "Проверить зону парковки у отеля"],
        },
        {
          time: "00:15",
          title: "Заселение в отель",
          transport: "walk",
          detail: "Регистрация, душ, сон. Завтра — спокойный день без раннего подъёма.",
          address: "← адрес отеля",
          cost: null,
        },
      ],
    },
    {
      id: "d2",
      date: "2026-08-04",
      label: "День 2 · Мягкий старт",
      weekday: "вторник",
      summary: "Отдых, центр, Невский, без дальних выездов",
      steps: [
        {
          time: "10:00",
          title: "Поздний завтрак у отеля",
          transport: "walk",
          detail: "Не спешим — организм после ночного поезда.",
          cost: 1200,
          costNote: "кафе",
        },
        {
          time: "12:00",
          title: "Невский проспект и каналы",
          transport: "walk",
          detail: "Казанский собор, Дом Книги, прогулка до Стрелки ВО или просто по центру.",
          address: "Невский пр., 28",
          lat: 59.9343,
          lon: 30.3351,
          cost: null,
        },
        {
          time: "15:00",
          title: "Эрмитаж или прогулка по Дворцовой",
          transport: "metro",
          detail: "Если есть силы — Эрмитаж (лучше билет онлайн). Если нет — Дворцовая площадь снаружи и Адмиралтейство.",
          address: "Дворцовая пл., 2",
          lat: 59.9398,
          lon: 30.3146,
          cost: 800,
          costNote: "×2 если в музей",
        },
        {
          time: "19:00",
          title: "Ужин и белая ночь",
          transport: "walk",
          detail: "Короткая прогулка по набережной. Рано лечь спать.",
          cost: 2500,
        },
      ],
    },
    {
      id: "d3",
      date: "2026-08-05",
      label: "День 3 · Екатерининский",
      weekday: "среда",
      summary: "Пушкин · Царское Село",
      steps: [
        {
          time: "09:00",
          title: "Завтрак · выезд",
          transport: "walk",
          cost: 800,
        },
        {
          time: "10:00",
          title: "Электричка Витебский → Пушкин",
          transport: "train",
          detail: "С Витебского вокзала до «Царское Село». В пути ~40 мин.",
          address: "Витебский вокзал",
          lat: 59.9136,
          lon: 30.2989,
          cost: 120,
          costNote: "×2",
        },
        {
          time: "11:00",
          title: "Екатерининский дворец",
          transport: "walk",
          detail: "Главная цель поездки. Янтарная комната — очередь; билет с временным слотом онлайн.",
          address: "Пушкин, Садовая ул., 7",
          lat: 59.716,
          lon: 30.3945,
          cost: 1500,
          costNote: "×2, дворец + парк",
          link: "https://tcspb.ru/",
        },
        {
          time: "14:30",
          title: "Обед в Пушкине",
          transport: "walk",
          cost: 2000,
        },
        {
          time: "16:00",
          title: "Парк · обратно в город",
          transport: "train",
          detail: "Прогулка по парку, затем электричка в СПб.",
          cost: 120,
          costNote: "×2",
        },
      ],
    },
    {
      id: "d4",
      date: "2026-08-06",
      label: "День 4 · Петергоф",
      weekday: "четверг",
      summary: "Фонтаны и парк",
      steps: [
        {
          time: "08:30",
          title: "Выезд к Балтийскому",
          transport: "metro",
          detail: "Метро до «Балтийская», далее электричка.",
          cost: 140,
          costNote: "×2 метро",
        },
        {
          time: "09:30",
          title: "Электричка → Новый Петергоф",
          transport: "train",
          cost: 120,
          costNote: "×2",
        },
        {
          time: "10:30",
          title: "Нижний парк · фонтаны",
          transport: "walk",
          detail: "Август — фонтаны работают. Взять крем от солнца и воду.",
          address: "Петергоф, Разводная ул., 2",
          lat: 59.886,
          lon: 29.908,
          cost: 1200,
          costNote: "×2 парк",
        },
        {
          time: "15:00",
          title: "Обед · возвращение",
          transport: "train",
          cost: 2500,
        },
      ],
    },
    {
      id: "d5",
      date: "2026-08-07",
      label: "День 5 · Выборг",
      weekday: "пятница",
      summary: "Выборг · Монрепо · по пути — Линдулово",
      steps: [
        {
          time: "07:30",
          title: "Поезд «Ласточка» · Финляндский",
          transport: "train",
          detail: "Финляндский вокзал → Выборг, ~1 ч 15 мин. Билеты заранее.",
          address: "Финляндский вокзал",
          lat: 59.9556,
          lon: 30.3564,
          cost: 1200,
          costNote: "×2",
        },
        {
          time: "09:30",
          title: "Выборгский замок",
          transport: "walk",
          address: "Выборг, замок",
          lat: 60.7156,
          lon: 28.7292,
          cost: 800,
          costNote: "×2",
        },
        {
          time: "12:00",
          title: "Старый город · обед",
          transport: "walk",
          cost: 2500,
        },
        {
          time: "14:30",
          title: "Парк Монрепо",
          transport: "carshare",
          detail: "Такси/каршеринг ~15 мин от центра Выборга. Скалы, сосны, Ладога.",
          lat: 60.718,
          lon: 28.768,
          cost: 600,
          costNote: "такси туда-обратно",
        },
        {
          time: "16:30",
          title: "По пути · Линдуловская роща (если успеем)",
          transport: "carshare",
          detail: "Заехать с севера в сторону СПб — кедровая роща у Рощино.",
          lat: 60.248,
          lon: 29.538,
          cost: 400,
          costNote: "доп. бензин",
        },
        {
          time: "18:00",
          title: "Поезд обратно в СПб",
          transport: "train",
          cost: 1200,
          costNote: "×2",
        },
      ],
    },
    {
      id: "d6",
      date: "2026-08-08",
      label: "День 6 · Валаам",
      weekday: "суббота",
      summary: "Ладога · теплоход на остров",
      steps: [
        {
          time: "07:00",
          title: "Каршеринг → Сортавала",
          transport: "carshare",
          detail: "Причал «Матка» / Валаам Cruises — билеты заранее.",
          address: "Сортавала",
          lat: 61.703,
          lon: 30.692,
          cost: 4500,
          costNote: "аренда на день",
        },
        {
          time: "11:00",
          title: "Теплоход → остров Валаам",
          transport: "bus",
          detail: "Переезд ~40–50 мин по Ладоге.",
          lat: 61.386,
          lon: 30.944,
          cost: 3000,
          costNote: "×2 теплоход",
          link: "https://valaam.ru/",
        },
        {
          time: "15:00",
          title: "Монастырь · прогулка",
          transport: "walk",
          cost: null,
        },
        {
          time: "18:00",
          title: "Возвращение в СПб",
          transport: "carshare",
          cost: 2000,
        },
      ],
    },
    {
      id: "d7",
      date: "2026-08-09",
      label: "День 7 · Отдых",
      weekday: "воскресенье",
      summary: "Восстановление после Валаама · без дальних выездов",
      steps: [
        {
          time: "10:30",
          title: "Поздний завтрак",
          transport: "walk",
          detail: "После карельского дня — не спешим. Завтра отъезд.",
          cost: 1200,
          costNote: "кафе",
        },
        {
          time: "12:30",
          title: "Летний сад или прогулка по каналам",
          transport: "walk",
          detail: "Тихая зелёная зона или короткая прогулка на теплоходе по каналам — по самочувствию.",
          address: "Летний сад",
          lat: 59.9443,
          lon: 30.3367,
          cost: 1600,
          costNote: "×2 если теплоход",
        },
        {
          time: "16:00",
          title: "Отдых в отеле · сборы",
          transport: "walk",
          detail: "Чай, упаковка вещей, ранний ужин. Рано лечь — завтра дорога домой.",
          cost: null,
        },
        {
          time: "19:00",
          title: "Спокойный ужин рядом с отелем",
          transport: "walk",
          cost: 2200,
        },
      ],
    },
    {
      id: "d8",
      date: "2026-08-10",
      label: "День 8 · Отъезд",
      weekday: "понедельник",
      summary: "Отель → 746У «Аврора» → Москва → мама в Электросталь",
      steps: [
        {
          time: "10:00",
          title: "Check-out из отеля",
          transport: "walk",
          detail: "Сдать ключи, проверить номер. Багаж с собой — вечером сразу на вокзал.",
          cost: null,
        },
        {
          time: "12:00",
          title: "Последняя прогулка / сувениры",
          transport: "walk",
          cost: 2000,
        },
        {
          time: "16:30",
          title: "Каршеринг → Московский вокзал",
          transport: "carshare",
          detail: "Запас до отправления 746У «Аврора» в 17:20. Посадка за 20–30 мин.",
          address: "Санкт-Петербург, Московский вокзал, пл. Восстания",
          lat: 59.9287,
          lon: 30.3617,
          cost: 800,
        },
        {
          time: "17:20",
          title: "Поезд 746У «Аврора» → Москва",
          transport: "train",
          detail: "Понедельник, 10 августа. Московский вокзал → Ленинградский вокзал.",
          cost: null,
        },
        {
          time: "22:58",
          title: "Прибытие · Ленинградский вокзал",
          transport: "train",
          detail: "Москва. В тот же вечер — отвезти маму домой.",
          address: "Москва, Ленинградский вокзал, Комсомольская пл.",
          lat: 55.7762,
          lon: 37.6553,
          cost: null,
        },
        {
          time: "23:15",
          title: "Каршеринг → Электросталь (мама)",
          transport: "carshare",
          detail: "От Ленинградского вокзала до Электростали. ~1–1,5 ч в зависимости от пробок.",
          address: "Москва → Электросталь",
          lat: 55.7842,
          lon: 38.4467,
          cost: 2500,
          costNote: "ориентир на каршеринг",
          tips: ["Проверить, что мама дошла до подъезда", "Заправка по необходимости"],
        },
      ],
    },
  ],

  /** Точки для анимации маршрута (порядок = движение по туру) */
  tourRoute: [
    { id: "msk-len", name: "Москва", subtitle: "Ленинградский вокзал · 17:45", lat: 55.7762, lon: 37.6553, phase: "moscow" },
    { id: "spb-mos", name: "Санкт-Петербург", subtitle: "Московский вокзал · 23:05", lat: 59.9287, lon: 30.3617, phase: "spb" },
    { id: "hotel", name: "Отель", subtitle: "База в Петербурге", lat: 59.9343, lon: 30.3351, phase: "spb" },
    { id: "pushkin", name: "Пушкин", subtitle: "Екатерининский дворец", lat: 59.716, lon: 30.3945, phase: "palaces" },
    { id: "peterhof", name: "Петергоф", subtitle: "Фонтаны и парк", lat: 59.886, lon: 29.908, phase: "palaces" },
    { id: "vyborg", name: "Выборг", subtitle: "Замок и старый город", lat: 60.7156, lon: 28.7292, phase: "north" },
    { id: "monrepos", name: "Монрепо", subtitle: "Парк у Ладоги", lat: 60.718, lon: 28.768, phase: "north" },
    { id: "lindulova", name: "Линдуловская роща", subtitle: "По пути на юг", lat: 60.248, lon: 29.538, phase: "north" },
    { id: "sortavala", name: "Сортавала", subtitle: "Причал на Валаам", lat: 61.703, lon: 30.692, phase: "karelia" },
    { id: "valaam", name: "Валаам", subtitle: "Монастырь на острове", lat: 61.386, lon: 30.944, phase: "karelia" },
    { id: "hotel-back", name: "Снова отель", subtitle: "Возвращение в СПб", lat: 59.9343, lon: 30.3351, phase: "spb" },
    { id: "spb-out", name: "Отъезд из СПб", subtitle: "Московский · 17:20", lat: 59.9287, lon: 30.3617, phase: "return" },
    { id: "msk-in", name: "Москва", subtitle: "Ленинградский · 22:58", lat: 55.7762, lon: 37.6553, phase: "return" },
    { id: "elektrostal", name: "Электросталь", subtitle: "Мама домой", lat: 55.7842, lon: 38.4467, phase: "return" },
  ],

  tourLegs: [
    { from: 0, to: 1, label: "746У «Аврора» · Москва → Петербург", transport: "train", durationMs: 6000 },
    { from: 1, to: 2, label: "Каршеринг до отеля", transport: "carshare", durationMs: 2200 },
    { from: 2, to: 3, label: "Екатерининский дворец", transport: "train", durationMs: 2800 },
    { from: 3, to: 4, label: "Петергоф · фонтаны", transport: "train", durationMs: 2600 },
    { from: 4, to: 5, label: "На север · Выборг", transport: "train", durationMs: 4500 },
    { from: 5, to: 6, label: "Монрепо", transport: "carshare", durationMs: 1800 },
    { from: 6, to: 7, label: "Линдулово · по пути", transport: "carshare", durationMs: 3200 },
    { from: 7, to: 8, label: "В Карелию · Сортавала", transport: "carshare", durationMs: 5000 },
    { from: 8, to: 9, label: "Теплоход · Валаам", transport: "bus", durationMs: 3500 },
    { from: 9, to: 10, label: "Обратно в Петербург", transport: "carshare", durationMs: 5500 },
    { from: 10, to: 11, label: "746У «Аврора» · домой", transport: "train", durationMs: 5500 },
    { from: 11, to: 12, label: "Приезд в Москву", transport: "train", durationMs: 1500 },
    { from: 12, to: 13, label: "Каршеринг · мама в Электросталь", transport: "carshare", durationMs: 4000 },
  ],

  mapPlaces: [
    { id: "hotel", name: "Отель", lat: 59.9343, lon: 30.3351, kind: "hotel" },
    { id: "moskovsky", name: "Московский вокзал (СПб)", lat: 59.9287, lon: 30.3617, kind: "station" },
    { id: "leningradsky", name: "Ленинградский вокзал (Москва)", lat: 55.7762, lon: 37.6553, kind: "station" },
    { id: "elektrostal", name: "Электросталь", lat: 55.7842, lon: 38.4467, kind: "city" },
    { id: "pushkin", name: "Екатерининский", lat: 59.716, lon: 30.3945, kind: "palace" },
    { id: "peterhof", name: "Петергоф", lat: 59.886, lon: 29.908, kind: "palace" },
    { id: "vyborg", name: "Выборг", lat: 60.7156, lon: 28.7292, kind: "north" },
    { id: "pavlovsk", name: "Павловск", lat: 59.686, lon: 30.434, kind: "palace" },
    { id: "lindulova", name: "Линдуловская роща", lat: 60.248, lon: 29.538, kind: "nature" },
  ],
};
